### ISSUE TITLE
Non-nullable fields are not being populated by package factories

### ISSUE THREAD

**Issue by chx2** [tipoff/bookings#85]
I am running into issues in other packages using model factories located within this package. I have found that `creator_id` and `updater_id` are not being consistently populated in model factories. The following models need to have them populated in their factories since the fields are indicated as non-nullable index fields. Otherwise they need to have the corresponding fields marked as nullable:

- [x] Bookings
- [x] Participants
- [x] Booking Categories
- [x] Rate
- [x] Rate Categories

**Comment by drewroberts** [comment]
They should all be non-nullable fields. Could you update the factories for me?
